from eDPM.model import FisherResults
import numpy as np

def check_if_not_identifieable(fsr: FisherResults):
    """This function will return `True` if a problem with identifieability is present.
    We check if the rank of the Fisher matrix is full.

    Note: We can only assert the identifieability of this particular configuration.
    It is not possible to make general statements by this simple routine about any
    structural non-identifieabilities.

    :param fsr: Results generated by an optimization or solving routine.
    :rtype: bool
    """
    return np.linalg.matrix_rank(fsr.S) != np.array(fsr.S.shape)[0]
